#!/usr/bin/env node
/**
 * Issueflow - 页面生成器
 * 
 * 将同步的 Issue 数据转换为 Next.js 页面
 * 
 * 用法:
 *   node scripts/generate-pages.js --input ./content/generated --output ./app
 */

const fs = require('fs');
const path = require('path');

// 解析命令行参数
function parseArgs() {
  const args = process.argv.slice(2);
  const options = {
    input: './content/generated',
    output: './app'
  };
  
  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--input':
        options.input = args[++i];
        break;
      case '--output':
        options.output = args[++i];
        break;
      case '--help':
      case '-h':
        console.log(`
Usage: node scripts/generate-pages.js [options]

Options:
  --input <path>   输入目录（同步后的 Issue 数据）
  --output <path>  输出目录（Next.js app 目录）
  --help, -h       显示帮助
`);
        process.exit(0);
    }
  }
  
  return options;
}

// 生成文章列表页面
function generateListPage(type, items) {
  const typeName = type.charAt(0).toUpperCase() + type.slice(1);
  const itemsJson = JSON.stringify(items, null, 2);
  
  let code = `// @generated by Issueflow - DO NOT EDIT
// Source: GitHub Issues

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${typeName}',
  description: '${typeName} 列表 - Issueflow Blog',
};

interface Item {
  number: number;
  title: string;
  slug: string;
  url: string;
  status: string;
  labels: string[];
}

const items: Item[] = ${itemsJson};

export default function ${typeName}Page() {
  return (
    <div className="container mx-auto px-4 py-8">
      <header className="mb-8">
        <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
          ${typeName}
        </h1>
        <p className="text-gray-400 mt-2">共 {items.length} 条记录</p>
      </header>
      
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {items.map((item) => (
          <article
            key={item.number}
            className="group relative bg-gradient-to-br from-gray-800/50 to-gray-900/50 
                       backdrop-blur-sm rounded-xl p-6 border border-gray-700/50
                       hover:border-blue-500/50 hover:shadow-lg hover:shadow-blue-500/10
                       transition-all duration-300"
          >
            <a href="/${type}/${item.slug}" className="block">
              <h2 className="text-xl font-semibold text-gray-100 group-hover:text-blue-400 
                             transition-colors line-clamp-2">
                {item.title}
              </h2>
              
              <div className="flex flex-wrap gap-2 mt-3">
                {item.labels
                  .filter(l => l.startsWith('category/') || l.startsWith('status/'))
                  .map(label => {
                    const isPublished = label.includes('published');
                    const isInProgress = label.includes('in-progress');
                    const colorClass = isPublished 
                      ? 'text-green-400 bg-green-500/20 border-green-500/30'
                      : isInProgress 
                        ? 'text-yellow-400 bg-yellow-500/20 border-yellow-500/30'
                        : 'text-gray-400 bg-gray-500/20 border-gray-500/30';
                    return (
                      <span
                        key={label}
                        className="px-2 py-1 text-xs rounded-full border " + colorClass
                      >
                        {label.replace('category/', '').replace('status/', '')}
                      </span>
                    );
                  })}
              </div>
              
              <p className="text-sm text-gray-500 mt-3">
                GitHub Issue #{item.number}
              </p>
            </a>
          </article>
        ))}
      </div>
    </div>
  );
}
`;
  return code;
}

// 生成文章详情页面
function generateDetailPage(type, slug, title) {
  return `// @generated by Issueflow - DO NOT EDIT

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${title}',
  description: '${title} - Issueflow Blog',
};

export default function ${type}DetailPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <article className="prose prose-invert prose-lg">
        <header className="mb-8 pb-8 border-b border-gray-700">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 
                         bg-clip-text text-transparent mb-4">
            ${title}
          </h1>
          <div className="flex items-center gap-4 text-gray-400">
            <span>📌 GitHub Issue</span>
            <span>•</span>
            <span>由 Issueflow 自动生成</span>
          </div>
        </header>
        
        <div className="bg-gradient-to-br from-gray-800/30 to-gray-900/30 
                        backdrop-blur-sm rounded-xl p-8 border border-gray-700/30">
          <p className="text-gray-400 text-center py-12">
            文章内容将从 GitHub Issue 自动同步。<br />
            请在 GitHub 上编辑 Issue #${slug} 的内容。
          </p>
        </div>
      </article>
    </div>
  );
}
`;
}

// 生成首页（聚合页）
function generateHomePage(allData) {
  const total = allData.total || 0;
  const byType = allData.by_type || {};
  
  let code = `// @generated by Issueflow - DO NOT EDIT
// Issueflow Blog 首页 - 聚合所有类型内容

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Issueflow Blog',
  description: '基于 GitHub Issues 的自动化博客系统',
};

const data = ${JSON.stringify(allData, null, 2)};

export default function HomePage() {
  return (
    <div className="container mx-auto px-4 py-8">
      {/* Hero Section */}
      <section className="text-center py-16">
        <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 
                       bg-clip-text text-transparent mb-4">
          Issueflow Blog
        </h1>
        <p className="text-xl text-gray-400 mb-8">
          基于 GitHub Issues 的自动化内容管理系统
        </p>
        <div className="flex justify-center gap-4">
          <a
            href="/articles"
            className="px-6 py-3 bg-gradient-to-r from-blue-500 to-blue-600 
                       hover:from-blue-600 hover:to-blue-700 rounded-lg font-medium
                       transition-all duration-300"
          >
            📝 查看文章
          </a>
          <a
            href="/ideas"
            className="px-6 py-3 bg-gradient-to-r from-purple-500 to-purple-600 
                       hover:from-purple-600 hover:to-purple-700 rounded-lg font-medium
                       transition-all duration-300"
          >
            💡 查看灵感
          </a>
        </div>
      </section>

      {/* Content Sections */}
      {Object.entries(data.by_type || {}).map(([type, items]) => (
        <section key={type} className="py-12 border-t border-gray-800">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-semibold text-gray-100">
              {type === 'article' ? '📝' : type === 'idea' ? '💡' : type === 'resource' ? '📦' : '📄'}
              {' '}{type.charAt(0).toUpperCase() + type.slice(1)}
            </h2>
            <a
              href={"/" + type}
              className="text-sm text-blue-400 hover:text-blue-300 transition-colors"
            >
              查看全部 →
            </a>
          </div>
          
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {(items || []).slice(0, 6).map((item) => (
              <a
                key={item.number}
                href={"/" + type + "/" + item.slug}
                className="block p-4 bg-gradient-to-br from-gray-800/40 to-gray-900/40
                           backdrop-blur-sm rounded-lg border border-gray-700/40
                           hover:border-blue-500/40 transition-all duration-300"
              >
                <h3 className="font-medium text-gray-100 line-clamp-2">{item.title}</h3>
                <p className="text-sm text-gray-500 mt-1">Issue #{item.number}</p>
              </a>
            ))}
          </div>
        </section>
      ))}

      {/* Stats */}
      <section className="py-12 border-t border-gray-800">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="text-center p-6 bg-gradient-to-br from-blue-500/10 to-blue-600/5 
                          backdrop-blur-sm rounded-xl">
            <p className="text-3xl font-bold text-blue-400">{total}</p>
            <p className="text-gray-400 mt-1">总内容</p>
          </div>
          {Object.entries(data.by_type || {}).map(([type, items]) => (
            <div key={type} className="text-center p-6 bg-gradient-to-br from-purple-500/10 to-purple-600/5 
                                        backdrop-blur-sm rounded-xl">
              <p className="text-3xl font-bold text-purple-400">{(items || []).length}</p>
              <p className="text-gray-400 mt-1">{type}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
`;
  return code;
}

// 主函数
async function main() {
  const options = parseArgs();
  
  const inputDir = path.resolve(options.input);
  const outputDir = path.resolve(options.output);
  
  if (!fs.existsSync(inputDir)) {
    console.error("错误: 输入目录不存在: " + inputDir);
    console.log('请先运行 sync-issues.js 同步 Issues');
    process.exit(1);
  }
  
  console.log("📄 正在生成页面...");
  console.log("   输入: " + inputDir);
  console.log("   输出: " + outputDir + "\n");
  
  // 读取索引文件
  const indexPath = path.join(inputDir, 'index.json');
  if (!fs.existsSync(indexPath)) {
    console.error("错误: 未找到 index.json，请先运行 sync-issues.js");
    process.exit(1);
  }
  
  const indexData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
  
  // 生成首页
  const homePagePath = path.join(outputDir, 'page.tsx');
  fs.mkdirSync(path.dirname(homePagePath), { recursive: true });
  fs.writeFileSync(homePagePath, generateHomePage(indexData), 'utf-8');
  console.log("✓ 首页: page.tsx");
  
  // 为每种类型生成列表页和详情目录
  for (const [type, items] of Object.entries(indexData.by_type || {})) {
    // 列表页
    const listPagePath = path.join(outputDir, type, 'page.tsx');
    fs.mkdirSync(path.dirname(listPagePath), { recursive: true });
    fs.writeFileSync(listPagePath, generateListPage(type, items), 'utf-8');
    console.log("✓ " + type + " 列表: " + type + "/page.tsx");
    
    // 详情目录（每个 slug 一个目录）
    for (const item of items) {
      const detailPath = path.join(outputDir, type, item.slug, 'page.tsx');
      fs.mkdirSync(path.dirname(detailPath), { recursive: true });
      fs.writeFileSync(
        detailPath,
        generateDetailPage(type, item.slug, item.title),
        'utf-8'
      );
    }
  }
  
  console.log("\n✅ 页面生成完成！");
  console.log("   共生成 " + Object.keys(indexData.by_type || {}).length + " 个类型页面");
}

main().catch(err => {
  console.error("错误:", err.message);
  process.exit(1);
});
